spring:
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          base-uri: https://kannanb2c.b2clogin.com/kannanb2c.onmicrosoft.com/
          credential:
          login-flow: sign-up-or-sign-in
          # logout-success-url: <your-logout-success-URL>
          user-flows:
            sign-up-or-sign-in: B2C_1_sampleSbApp
            # profile-edit: profile
            # password-reset: password
          # user-name-attribute-name: <your-user-name-attribute-name>
